### ISSUE TITLE
Scenario: Bot sends a message in Сhat language

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#108]
## Details

Bot should send messages in the language set by users.
The default language should be English.

## Subtasks

- [ ] Add a scenario file
- [ ] Create an xstate diagram
- [ ] https://github.com/team-work-tools/team-work-telegram-bot/issues/50
- [x] Select language for a message based on the chat settings (https://github.com/team-work-tools/team-work-telegram-bot/pull/92)
