### ISSUE TITLE
Write tests with coverage

### ISSUE THREAD

**Issue by belyakova-anna** [team-work-tools/team-work-telegram-bot#110]
## Subtasks

- [x] Discuss with the team what functionality needs to be covered with tests
- [x] Determine test type
- [x] Define a test writing tool
