### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by belyakova-anna** [team-work-tools/team-work-telegram-bot#111]
## Subtasks

- [x] Linting of source code
- [x] Building testable snapshot (if needed)
- [x] Testing
- [x] Reports on linting and coverage
- [x] Some other tool(s) of your choice relevant to your stack
