### ISSUE TITLE
Write TDD tests

### ISSUE THREAD

**Issue by belyakova-anna** [team-work-tools/team-work-telegram-bot#112]
## Subtasks

- [x] Determine for what functionality tests will be written
- [x] Determine test type
- [x] Define a test writing tool
