### ISSUE TITLE
Scenario: User creates a recurring message

### ISSUE THREAD

**Issue by belyakova-anna** [team-work-tools/team-work-telegram-bot#115]
## Details

The user should be able to create a recurring message with a specified title, start time, end time, recurring period and text

## Subtasks

- [ ] Describe the scenario
- [ ] Draw XState diagram
- [ ] https://github.com/team-work-tools/team-work-telegram-bot/issues/114
