### ISSUE TITLE
Scenario: User edits a recurring message

### ISSUE THREAD

**Issue by belyakova-anna** [team-work-tools/team-work-telegram-bot#117]
## Details

The user should be able to edit the title, start time, end time, recurring period, and text of an existing recurring event. 

## Subtasks

- [ ] Describe the scenario
- [ ] Draw XState diagram
- [ ] https://github.com/team-work-tools/team-work-telegram-bot/issues/116
