### ISSUE TITLE
Update issue templates

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#121]
## Subtasks

- [x] add a link to the glossary
- [x] specify that there MUST be at least one subtask (https://github.com/team-work-tools/team-work-telegram-bot/pull/122)
- [x] specify what other materials can be linked in the details section (https://github.com/team-work-tools/team-work-telegram-bot/pull/122)
- [x] Use an [issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) (https://github.com/team-work-tools/team-work-telegram-bot/pull/125)
- [x] https://github.com/team-work-tools/team-work-telegram-bot/issues/123
