### ISSUE TITLE
Move the glossary to `docs`

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#123]
## Details

Currently, we have two glossaries - [one](https://github.com/team-work-tools/team-work-telegram-bot/blob/main/docs/configuration/glossary.md), [two](https://github.com/team-work-tools/team-work-telegram-bot/blob/main/docs/configuration/scenarios/glossary.md).

This isn't optimal because there is some term duplication.

Also, the main glossary is in the `docs/configuration` directory and may be moved in the future.
Then, many links will be broken.
I suggest we store the glossary in the `docs` directory.

## Subtasks

- [x] Move [glossary](https://github.com/team-work-tools/team-work-telegram-bot/blob/main/docs/configuration/glossary.md) to `docs`. (https://github.com/team-work-tools/team-work-telegram-bot/pull/124)
- [x] Update links. (https://github.com/team-work-tools/team-work-telegram-bot/pull/124)
- [ ] Remove the glossary from the sprint documentation
