### ISSUE TITLE
Update git workflow

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#133]
### Details

Currently, the [git workflow](https://github.com/team-work-tools/team-work-telegram-bot/blob/main/docs/configuration/git-workflow-process.md) document uses outdated terms and doesn't provide up-to-date info on working with issues.

### Subtasks

- [ ] Add a link to the new glossary
- [ ] Remove old terms
- [ ] Update process of working with branches
- [ ] Update process of working with issues
