### ISSUE TITLE
Scenario: create a task

### ISSUE THREAD

**Issue by plaffyyy** [team-work-tools/team-work-telegram-bot#136]
### Details

An opportunity for user to set text, deadlain, reminder period and responsible people for this task

### Subtasks

- [ ] set text for task
- [ ] set deadlain for task
- [ ] set reminder period for task
- [ ] set responsible people for task
