### ISSUE TITLE
Support topics

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#14]
### Problem

Currently, the bot may not be able to reply in the group topic where it received a command.

This inability is because we use `message.chat.id` to get the message source.

https://github.com/team-work-tools/team-work-telegram-bot/blob/0cb8bbf26aa1ba0351481a83d4815c501f6ee01b/bot/filters.py#L26

https://github.com/team-work-tools/team-work-telegram-bot/blob/0cb8bbf26aa1ba0351481a83d4815c501f6ee01b/bot/state.py#L21

### Acceptance test

1. I add the bot to our project group on Telegram
1. I switch to the `Test` topic
1. I send `/start`
1. I send `/join`
1. I send `/set_meetings_time <current time + one minute>`
1. Expected result: I receive daily messages in one minute in the `Test` topic

## Subtasks

- [ ] Edit the database schema to allow topics.
- [ ] Remember the topic where the bot received a command.
- [ ] Reply to commands in that topic.

**Comment by deemp** [comment]
Superseded by https://github.com/team-work-tools/team-work-telegram-bot/pull/65
