### ISSUE TITLE
Improve issue templates

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#143]
### Details

Current problems:
- There's no brief summary what should go into Details and Subtasks.
- Blank issues are enabled.
- What are "the terms"? https://github.com/team-work-tools/team-work-telegram-bot/blob/3d8f08053ca62dd8c63a4b823dfc75ad456d4378/.github/ISSUE_TEMPLATE/task.yml?plain=1#L12
- Text in issue forms under `Subtasks` is too long and contains info not related to issue creation.

### Subtasks

- [ ] Disable blank issues - use [config.yml](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) instead of [config.yaml](https://github.com/team-work-tools/team-work-telegram-bot/blob/3d8f08053ca62dd8c63a4b823dfc75ad456d4378/.github/ISSUE_TEMPLATE/config.yaml)
- [ ] Use just "terms" instead of the "terms"
- [ ] Add sections in the text under Subtasks

**Comment by deemp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Abra](https://trello.com/c/IF5gmRPH/1-abra)
