### ISSUE TITLE
Enable authentication in the database

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#148]
### Details

This is essentially a subtask from https://github.com/team-work-tools/team-work-telegram-bot/issues/6.

### Subtasks

- [x] Use a password (https://github.com/team-work-tools/team-work-telegram-bot/pull/149)
- [x] Use a username (https://github.com/team-work-tools/team-work-telegram-bot/pull/149)
- [x] Update sample `.env` config (https://github.com/team-work-tools/team-work-telegram-bot/pull/149)
