### ISSUE TITLE
Handle the `/reset` command

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#157]
### Subtasks

- [x] Reset the Chat state (https://github.com/team-work-tools/team-work-telegram-bot/pull/142)
- [ ] Remove all scheduled daily messages
- [ ] Remove all reminders
