### ISSUE TITLE
Write scenario for /set_reminder_period command

### ISSUE THREAD

**Issue by belyakova-anna** [team-work-tools/team-work-telegram-bot#38]
## Subtasks

- [x] Choose a suitable name (https://github.com/team-work-tools/team-work-telegram-bot/pull/72)
- [x] Make a diagram (https://github.com/team-work-tools/team-work-telegram-bot/pull/72)
- [x] Approve with developers
