### ISSUE TITLE
Describe the common git workflow process

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#58]
## Description

Teams need to submit the description of the Git workflow process as a deliverable for the Assignment 3.

## Subtasks

- [ ] Add the file `docs/configuration/git-workflow-process.md`
- [ ] Describe the workflow process there
- [ ] Add a Git graph diagram for the process
