### ISSUE TITLE
Sprint Implementation: Conduct daily meetings on Monday-Friday in a group or a private chat

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#78]
## Implements

- https://github.com/team-work-tools/team-work-telegram-bot/issues/77

## Subtasks

Note: subtasks were implemented somewhere by https://github.com/team-work-tools/team-work-telegram-bot/commit/e8b2912d9fafa530ed8982cd395467597400fac1

- [x] Implement scheduling at a given time periodic daily meeting questions
- [x] Send questions only on Monday-Friday
- [x] Send questions only to joined users
- [x] Handle the case when no one has joined
