### ISSUE TITLE
Add User Acceptance Tests section to the scenario template

### ISSUE THREAD

**Issue by deemp** [team-work-tools/team-work-telegram-bot#81]
## Details

Scenarios describe what happens internally and what a user sees in different cases.
Customer and developers need a way to check that scenarios work correctly.

## Subtasks

- [ ] Update the scenario template to include the `User Acceptance Tests` section
- [ ] Add the `docs/configuration/tests/user-acceptance-tests` directory
- [ ] Create there a test template in the `uat-template.md` file
- [ ] Sections in the template:
  - Environment - initial conditions
  - Scenario - how the interaction between the user and bot looks from outside - a sequence diagram using mermaid
